name: cd-fcs-base
recipe: laravel
config:
  webroot: ./public
  php: 8.3
  cache: none
  composer_version: 2-latest

services:
  appserver:
    overrides:
      volumes:
        - ${HOME}/.composer/auth.json:/var/www/.composer/auth.json:ro
